version: '3'
services:
  postgres:
    build: postgres/
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: app/
    ports:
      - "8080:8080"
volumes:
