version: "3.5"
services:
  postgres:
    build:
      context: ./core/src/main/resources/db/schema
    container_name: iv-db
    environment:
      - POSTGRES_PASSWORD=brainweb
    ports:
      - 5432:5432
  core:
    image: brainweb/interview
    restart: on-failure
    environment:
      - DB_HOSTNAME=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
